sudo: required

services:
  - docker

install: true

script:  
  - docker build -t swirrl/innovateuk-projects:build_$TRAVIS_BUILD_NUMBER .
  - docker push swirrl/innovateuk-projects:build_$TRAVIS_BUILD_NUMBER
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

branches:
  only:
    - master